<?php

use Monolog\Handler\StreamHandler;
use Monolog\Logger;

date_default_timezone_set('UTC');

include 'vendor/autoload.php';

$scanMode = INI_SCANNER_NORMAL;
if (version_compare(PHP_VERSION, '5.6.1') >= 0) {
    $scanMode = INI_SCANNER_TYPED;
}

$commando = new \Commando\Command();

// Define CLI Args
$commando->option('l')
    ->aka('logname')
    ->describedAs('Single Log file to check. Must include full path. Will override the logfile Array found in the config.')
    ->must(function ($filename)
    {
        return file_exists($filename);
    });

$commando->option('g')
    ->aka('glob')
    ->describedAs('Single filepath pattern to check. Will override the globList Array found in the config.');

$commando->option('t')
    ->aka('to')
    ->describedAs('Email address to send the log to if it has changed. Will append this email to the list in the array');

$commando->option('a')
    ->aka('age')
    ->describedAs('Age in seconds. Monitored files *NEWER* than this age will be emailed. (Will override value in config file.)');

$commando->option('o')
    ->aka('overrideTo')
    ->describedAs('Boolean. All other arguments are overrides, but by default --to is additive. Set this to true to make it override. NB: if --to is not also set this option does nothing.')
    ->boolean()
    ->default(false);

$commando->option('c')
    ->aka('config')
    ->describedAs('Full or Relative path to config file. A config file is INI based see ./sample.config.ini for an example. Defaults to \'config.ini\' in the log monitor directory.')
    ->default('config.ini');

$config = parse_ini_file($commando['config'],true,$scanMode);

if (!empty($commando['logname'])) {
    $config['log_list']['logs'] = array($commando['logname']);
}
if (!empty($commando['glob'])) {
    $config['log_list']['globList'] = array($commando['glob']);
}
if (!empty($commando['to'])) {
    $config['mailer']['to'][] = $commando['to'];
    if ($commando['overrideTo']) {
        $config['mailer']['to'] = array($commando['to']);
    }
}

if (!empty($commando['age'])) {
    $config['log_list']['age'] = $commando['age'];
}

$now = new DateTime;

// Age in seconds.
$allowedAge = $config['log_list']['age'];

$logFiles = array();

// List of log files to monitor.
$filenames = $config['log_list']['logs'];

// Add in any files found via globbing:
$globList = $config['log_list']['globList'];
if (!empty($globList)) {
    foreach ($globList as $globPattern) {
        foreach (glob($globPattern, GLOB_BRACE) as $fileNamePath) {
            if (file_exists($fileNamePath)) {
                $filenames[] = $fileNamePath;
            }
        }
    }
}

/**
 * A Closure to send the email with any attachments.
 *
 * @param $attachments array
 */
$sendMail = function ($attachments) use ($now, $config)
{
    $logger = new Logger('mailError');
    $logger->pushHandler(new StreamHandler(__DIR__ . 'LogMonitor.log', Logger::INFO));

    if (!empty($attachments)) {
        $hostname = gethostname() ? : php_uname('n');
        $subject = '[Log Monitor][' . $hostname . '] ' . $now->format('Y-m-d H:i:s O');
        $message = 'This email was generated by the Log File Monitor running on ' . $hostname . '. The attached file(s) have changed within the set timeframe. This report was generated at ' . $now->format('Y-m-d H:i:s O') . '.';


        $mail = new PHPMailer;

        $mail->isSMTP();
        $mail->Host = $config['mailer']['host'];          // Specify main and backup SMTP servers
        $mail->SMTPAuth = $config['mailer']['auth'];      // Enable SMTP authentication
        $mail->Username = $config['mailer']['username'];  // SMTP username
        $mail->Password = $config['mailer']['password'];  // SMTP password
        $mail->SMTPSecure = $config['mailer']['secure'];  // Enable TLS encryption, `ssl` also accepted
        $mail->Port = $config['mailer']['port'];          // TCP port to connect to

        $from = (!empty($config['mailer']['fromAddress']) ? $config['mailer']['fromAddress'] : $config['mailer']['username']);
        $fromName = (!empty($config['mailer']['fromName']) ? $config['mailer']['fromAddress'] : '');

        $mail->setFrom($from, $fromName);

        foreach ($config['mailer']['to'] as $address) {
            $mail->addAddress($address);
        }

        $replyTo = (!empty($config['mailer']['replyAddress']) ? $config['mailer']['replyAddress'] : null);
        if (!is_null($replyTo)) {
            $replyName = (!empty($config['mailer']['replyName']) ? $config['mailer']['replyName'] : '');
            $mail->addReplyTo($replyTo, $replyName);
        }

        $mail->isHTML(true);

        $message .= '<br>' . PHP_EOL;
        $message .= 'Attachments:<br>'. PHP_EOL;
        $message .= '<ul>'.PHP_EOL;
        $attachList = [];
        foreach ($attachments as $attachment) {
            $attached = $mail->addAttachment($attachment->fullPath, $attachment->filename);
            if ($attached) {
                if (!in_array($attachment->fullPath, $attachList)) {
                    $message .= '<li>' . $attachment->fullPath . '</li>' . PHP_EOL;
                }
                $attachList[] = $attachment->fullPath;
            }

        }
        $message .= '</ul>';

        $mail->Subject = $subject;
        $mail->Body    = $message;

        // TODO: Since echo isn't helpful during a cron (it is written to /var/spool/mail/[user] we should investigate a better alert for errors in sending.
        if(!$mail->send()) {
            $logger->error('Message could not be sent.');
            $logger->error('Mailer Error: ' . $mail->ErrorInfo);
            $logger->info($message);
        } else {
            $logger->info('Message has been sent');
            $logger->info($message);
        }

    }
};

/**
 * Closure to verify the age of a log file and add it to the attachment list if too recent.
 *
 * @param $filename string
 */
$verifyAndAttachLog = function ($filename) use (&$logFiles, $allowedAge)
{
    if (file_exists($filename)) {

        $rightNow = time();
        $fileTime = filemtime($filename);

        $fileAge = $rightNow - $fileTime;

        if ($fileAge <= $allowedAge) {
            $fileData = new stdClass;
            $fileData->filename = basename($filename) . '-' . date('YmdHisO',$rightNow) . '.log';
            $fileData->fullPath = $filename;

            $logFiles[] = $fileData;
        }
    }
};

foreach ($filenames as $filename) {
    $verifyAndAttachLog($filename);
}

$sendMail($logFiles);
